import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://docs.globdrem.com/real-estate-company/overview">Real Estate Acquisition!</a>
        </h1>

        <p className={styles.description}>
          Get started by entering real estate information{' '}
        </p>

        <div className={styles.grid}>
          <a href="https://docs.globdrem.com/real-estate-company/overview" className={styles.card}>
            <h2>REIT &rarr;</h2>
            <p>Information about REIT!</p>
          </a>

          <a href="https://docs.globdrem.com/real-estate-company/overview" className={styles.card}>
            <h2>Asset &rarr;</h2>
            <p>Information about the Asset!</p>
          </a>

          <a
            href="https://docs.globdrem.com/real-estate-company/overview"
            className={styles.card}
          >
            <h2>Review &rarr;</h2>
            <p>Review Assets proposed by REIT!</p>
          </a>

          <a
            href="https://docs.globdrem.com/real-estate-company/overview"
            className={styles.card}
          >
            <h2>Purchase &rarr;</h2>
            <p>
              Notary, Payment and Purchase Asset!
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/drem.png" alt="DREM marketplace" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
