name: Create docker image

on: [ push ]

jobs:
  multi:
    runs-on: [ubuntu-latest]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - 
        name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
            timezone: Europe/Bratislava  
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: scholtz2
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Get current date
        id: datehour
        run: echo "::set-output name=datehour::$(date +'%Y-%m-%d-%H')"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./market/api/DREM-API/DREM-API/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            scholtz2/drem-api:latest,scholtz2/drem-api:${{ steps.date.outputs.date }},scholtz2/drem-api:${{ steps.datehour.outputs.datehour }}

      - name: exec
        uses: fifsky/ssh-action@master
        with:
          command: |
            ./run.sh ${{ steps.date.outputs.date }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.HOSTPORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.PRIVATE_KEY}}